apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v2ws
  template:
    metadata:
      labels:
        app: v2ws
    spec:
      containers:
      - image: byxiaopeng/ssv2ray
        name: v2ws

---

apiVersion: v1
kind: Service
metadata:
  name: v2ws
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "http-port-tcp"
    port: 8080
  selector:
    app: v2ws
